netbox:
  url: "https://localhost:8000"
  token: "your-api-token-here"
  verify_ssl: false
  port: 8000

excel:
  file_path: "test.xlsx"
  sheet_name: "Лист1"
  start_row: 4

mappings:
  device_types:
    switch: 
      manufacturer: "Cisco"
      model: "Catalyst 2960"
      slug: "catalyst-2960"
    server:
      manufacturer: "Dell" 
      model: "PowerEdge R740"
      slug: "poweredge-r740"
    router:
      manufacturer: "Cisco"
      model: "ASR 1000"
      slug: "asr-1000"
    firewall:
      manufacturer: "Cisco"
      model: "ASA 5500"
      slug: "asa-5500"
    ups:
      manufacturer: "APC"
      model: "Smart-UPS 3000"
      slug: "smart-ups-3000"
    wlc:
      manufacturer: "Cisco"
      model: "Wireless Controller"
      slug: "wlc-5508"
    storage:
      manufacturer: "Dell"
      model: "Compellent"
      slug: "compellent-sc4020"
    radio:
      manufacturer: "Mikrotik"
      model: "Wireless Radio"
      slug: "wireless-radio"

  device_roles:
    switch: "L2 Switch"
    server: "Server"
    router: "Router"
    firewall: "Firewall"
    ups: "UPS"
    wlc: "Wireless Controller"
    storage: "Storage Controller"
    radio: "Radio Bridge"

  site_mapping:
    STM: "Stadium-Main"
    STU: "Stadium-Upper"
    TPU: "Technical-Power-Unit"

defaults:
  device_status: "active"
  interface_type: "virtual"
  vrf_default: "MGMT"
